dist: focal
language: python
python: "3.10"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
services:
  - docker
env:
  global:
    - TRAVIS_CI: "true"
    - TIMESTAMP: $(date '+%Y%m%d%H%M%S')
    - APPLICATION_NAME: "docs-build"
before_install:
  - cp theme/_config.yml.example theme/config.yml
  - pip install awscli
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
install: true
script:
  - docker build -t ${DOCKER_REPO} .
before_deploy:
  - if [ ! -d deploy_scripts ]; then git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git; fi
  - bash deploy_scripts/containers/push_image_to_ecr.sh $APPLICATION_NAME
deploy:
  provider: script
  script: bash deploy_scripts/containers/deploy_image_lambda.sh
  on:
    branch: base
notifications:
  email: false
