language: generic
services:
  - docker
env:
  global:
    - TRAVIS_CI: "true"
before_install:
  - cp theme/_config.yml.example theme/config.yml
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
install: true
script:
  - docker-compose up
