services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.18.0
    - TRAVIS_CI: "true"
before_install:
  - cp theme/_config.yml.example theme/config.yml
  - cp config.json.sample config.json
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker-compose up -d
install: true
