language: generic
services:
  - docker
env:
  global:
    - TRAVIS_CI: "true"
    - CONTAINER: docs
before_install:
  - cp theme/_config.yml.example theme/config.yml
  - cp config.json.sample config.json
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
install:
  - docker-compose up -d
script:
  - ./wait-for-it.sh $CONTAINER:4000 -- echo "done"
  - ./cibuild
