language: generic
services:
  - docker
env:
  global:
    - TRAVIS_CI: "true"
before_install:
  - cp theme/_config.yml.example theme/config.yml
  - pip install awscli
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
install: true
script:
  - docker-compose up
deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: base
notifications:
  email: false
