FROM python:3.12-slim

# Environment setup
ENV DEBIAN_FRONTEND=noninteractive
ENV CONTAINER_ROOT=/home/docs/docs-build/
ENV RUBY_VERSION=3.2.4

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      make gcc g++ curl gpg git \
      apache2 \
      inotify-tools \
      ruby \
      ruby-dev \
      build-essential \
      libffi-dev \
      libssl-dev \
      zlib1g-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set up Ruby
RUN gem install bundler --no-document && \
    gem install jekyll --no-document && \
    mkdir -p /usr/local/rvm/gems/ruby-${RUBY_VERSION}/wrappers && \
    ln -s $(which jekyll) /usr/local/rvm/gems/ruby-${RUBY_VERSION}/wrappers/jekyll

# Install Python dependencies
ADD requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Configure Apache
COPY apache/httpd.conf /etc/apache2/sites-enabled/000-default.conf

WORKDIR ${CONTAINER_ROOT}
ADD . .

# Expose port
EXPOSE 4000

CMD ["./entrypoint.sh"]
